### ISSUE TITLE
Create Popup on a Match

### ISSUE THREAD

**Issue by mksavic** [gcivil-nyu-org/fall2019-cs-gy-6063-team-debug_entities#110]
### Front End

If two users end up matching, we need a popup that says something along the lines of "Congrats, you matched with `User 2`!" In that popup should contain two buttons. One should say "Keep Swiping" and the other should say "Message `User 2`".

### Back End

This code will replace the `pass` described in #108.

*   If the user clicks "Keep Swiping", the popup should disappear and they should be able to continue swiping through people as normal.
*   If the user clicks "Message `User 2`", nothing should happen for now. (Implement the same way as above for the sake of the demo.)

**Comment by vmoros** [comment]
It seems like this issue is describing what should happen to the second person to swipe right i.e. they swipe right on someone who has already swiped right on them so they immediately get this match popup.

But what should happen to the first person who swiped? They might not even be using ShowUp at the time. Should they get a notification next time they log in?
