### ISSUE TITLE
Create Squad Stack

### ISSUE THREAD

**Issue by vmoros** [gcivil-nyu-org/fall2019-cs-gy-6063-team-debug_entities#143]
For now, let's make squads globally i.e. a user has a squad and they're with that squad for all events.
### Back End
We'll need a new Squad model and then we'll probably need to add a foreign key from the user model to the squad model.

This would be better than having a many to many field in the Squad model because that would allow a user to be in several squads, which we don't want.

**Comment by mksavic** [comment]
This issue entails taking user input (an email address) and adding that email address to your squad (along with verification).

**Comment by kavinshah** [comment]
need more clarity on it's working from front end perspective before proceeding ahead.

**Comment by jawooson** [comment]
@kavinshah I updated the front end description, lmk if it is still unclear!

**Comment by kavinshah** [comment]
@jawooson  

1. still unclear on how squads are formed? Where exactly do users get an option to form a squad?
2. Do a single user squad form when a user signs up? or when they mark interested for any event? since squads are same across all events, I think it's former
3. Whose email address be used to reference a squad? is it even referenced by single email or multiple email ids? if single person, then whose email id is used to reference when 2 squads merge?

**Comment by mksavic** [comment]
@kavinshah 
1. Squad profiles will exist at `/squad/<sid>` where `<sid>` is the squad id/primary key. Similar to `/u/<uid>/edit`, we will have a `/squad/<sid>/edit` where squad profiles can be edited.
1. Once a user has verified their email address they are placed into a squad of one.
1. No email address should be associated with the squad. Django provides default primary keys, you should use that.
