### ISSUE TITLE
pre loaded scripts

### ISSUE THREAD

**Issue by kavinshah** [gcivil-nyu-org/fall2019-cs-gy-6063-team-debug_entities#152]
1. email template needs to be manually changed by running a script. Should change on startup without any additional command. Can find a way to trigger that command on application startup for now.
2. default users also need to be added on startup to prevent running script for multiple users everytime.
3. need to think a way to run pull_seatgeek_data also if there are no events in Concerts table

**Comment by mksavic** [comment]
> 1. email template needs to be manually changed by running a script. Should change on startup without any additional command. Can find a way to trigger that command on application startup for now.

The command is `python manage.py set_name` and it actually only needs to be called once per DB initialization. There really isn't any other way to go about this since the domain and site name are set in the Sites model. The default value in the sites model is example.com.

> 2. default users also need to be added on startup to prevent running script for multiple users everytime.

What do you mean by this? I don't think it would be a good idea to have default users added on startup since that doesn't happen when ShowUp is deployed (it shouldn't).

> 3. need to think a way to run pull_seatgeek_data also if there are no events in Concerts table

Can you elaborate on this? `python manage.py pull_seatgeek_data` works if there are no events in the Concerts table already.

**Comment by mksavic** [comment]
@kavinshah

**Comment by mksavic** [comment]
Closing.
