### ISSUE TITLE
No notification of squad invitations

### ISSUE THREAD

**Issue by jackxujh** [gcivil-nyu-org/fall2019-cs-gy-6063-team-debug_entities#241]
The page says I can invite people to join my squad: "*Enter a user's email address to send them a request to join squads. If they accept, you will join squads.*" But I don't get notifications in the website or in email. So I cannot accept in any terms. Rather, the other user had to also initiate an invitation on their end, and then the system matches the two users.

**Comment by Vedanth15** [comment]
@jackxujh Once you send an invite to a user on the application to join a squad, you are not notified, instead the person whom you send the request has an invite in his/her `requests` tab. Once you send an invite I don't see how you can accept it or maybe I couldn't understand what you are trying to convey. Person you sent the request to should accept it. Application doesn't allow you to add yourself to the squad.

**Comment by mksavic** [comment]
### Front End

Have the following popup appear when you successfully submit a squad request. Have it say "You sent a squad request to example@example.com! If they accept, both of your squads will merge." Change it so that it does not redirect you back to `/s/<sid>` (stay on `/s/<sid>/edit`).

<img width="1280" alt="Screen Shot 2019-12-05 at 3 30 57 PM" src="https://user-images.githubusercontent.com/15850452/70271369-3f11d580-1774-11ea-857e-75279b48531b.png">

**Comment by vmoros** [comment]
Whoever does this issue, check this out:
https://stackoverflow.com/questions/56181675/how-to-make-global-context-variable-in-django

**Comment by mksavic** [comment]
@vmoros thank u. that was very helpful.
