### ISSUE TITLE
Implement Messaging

### ISSUE THREAD

**Issue by Vedanth15** [gcivil-nyu-org/fall2019-cs-gy-6063-team-debug_entities#6]
Once the user connects to other users, we need an interface for them to communicate. So if they connect i.e enable communication between them using a chat box. Any of the users should be able to attach files in the conversation and also allow emoticons( the world runs on emojies :p ). Make sure that both the users can send messages to each other simultaneously. Conversations should be able to scroll up and down to view previous messages.

**Comment by vmoros** [comment]
Some notes for myself: I tested [pinax-messages](https://github.com/pinax/pinax-messages) and [django-messages](https://github.com/arneb/django-messages). I preferred pinax-messages but it only does user-to-user messages. That would work for us, but it's not ideal. I think a homemade approach is our best option, so that we can have messages between squads, instead of between individual users.
